version: '2'
services:
  db:
    image: mysql:latest
    volumes:
      - eatdb_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=eatdb
      - MYSQL_USER=eatclient
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
  web:
    build: ./eatdb
    volumes: 
      - ./eatdb:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  eatdb_volume:
